// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeskzaodgfveidyeghbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlc2t6YW9kZ2Z2ZWlkeWVnaGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzMwNjksImV4cCI6MjA3MzgwOTA2OX0.ZmkMokmSNUrBuYGfE0DyuY3F0NtfFJawcjicZdGUd_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'liberty-auth-token',
    lock: 'navigator-lock-liberty',
  }
});